### PR TITLE
Ikfe/configure to access assets outside src

### PR DESCRIPTION
**Pull request by ingridkarinaf**

### CODE REVIEW

**Comment by ocni-dtu** [comment]
```
Error: src/cardGrid/cardGrid.stories.tsx(5,34): error TS6059: File '/home/runner/work/arkitema-ui/arkitema-ui/packages/layout/.storybook/assets/index.ts' is not under 'rootDir' '/home/runner/work/arkitema-ui/arkitema-ui/packages/layout/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via '../../.storybook/assets' from file '/home/runner/work/arkitema-ui/arkitema-ui/packages/layout/src/cardGrid/cardGrid.stories.tsx'
    Matched by include pattern '.storybook/assets' in 'tsconfig.json'
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @arkitema/layout@0.1.2 
npm ERR!   at location: /home/runner/work/arkitema-ui/arkitema-ui/packages/layout 
```

**Comment by ingridkarinaf** [comment]
> 
What test gave the error?

**Comment by ocni-dtu** [comment]
`src/cardGrid/cardGrid.stories.tsx`

https://github.com/Arkitema/arkitema-ui/actions/runs/5354009645/jobs/9710516990

**Comment by ingridkarinaf** [comment]
> `src/cardGrid/cardGrid.stories.tsx`
> 
> https://github.com/Arkitema/arkitema-ui/actions/runs/5354009645/jobs/9710516990

I can't reproduce the error locally by running build, but will try to push again with some changes

**Pull request merged**
